common:
  seed: 42
  prompt_dir: results/prompts
  answers_dir: results/answers
  judgements_dir: results/judgements
inference:
  temperature: 0
  model: speakleash/Bielik-11B-v3.0-Instruct
  base_url: https://llmlab.plgrid.pl/api/v1
  api_key: "@format {env[PLGRID_API_KEY]}"
  timeout: 120
judgement:
  temperature: 0
  resume: None
  model: qwen/qwen3-32b
  base_url: https://api.groq.com/openai/v1
  api_key: "@format {env[GROQ_API_KEY]}"
  timeout: 60